spring.application.name=Honey Shop Application

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.hibernate.persister.entity=ERROR

users.default-user.name=Galina
users.default-user.email=galina.k.georgieva@abv.bg
users.default-user.country=BULGARIA
users.default-user.password=${DEFAULT_ADMIN_PASSWORD:123456789}